interface Resources {
  account: {
    accountInfo: "Account infomation";
    name: "Name";
    gender: {
      root: "Gender";
      male: "Male";
      female: "Female";
      other: "Other";
    };
    dayOfBirth: "Date of birth";
    address: "Address";
    phone: "Phone number";
    aboutYou: "About you";
    updateInfo: "Update info";
    successUpdate: "Update successful";
    failUpdate: "Update failed! please contact us";
    changeYourPassword: "Change your password";
    newPassword: "New password";
    confirmPassword: "Confirm password";
    changePassword: "Change password";
  };
  addBusiness: {
    error: {
      nameRequired: "Name is required";
      typesRequired: "Types is required";
      descriptionRequired: "description is required";
      categoriesRequired: "categories is required";
      atLeastOneCats: "At least one category is required";
      contactType: "Contact type is required";
      contactValue: "Contact value is required";
      displayedRequired: "Displayed address is required";
      countryRequired: "Country is required";
      atLeastOneimages: "At least one image is required";
      thumbnailRequired: "Thumbnail is required";
      missingField: "Missing field";
    };
    successfulAdd: "Business added successfully!";
    failAdd: "Failed to add business.";
    goBack: "Go back";
    submit: "Submit";
    addTag: "Add tag";
    addContact: "Add contact";
    updateContact: "Update contact";
    stepTitle: {
      infomation: "Infomation";
      contacts: "Contacts";
      openTime: "Open Time";
      images: "Images";
    };
    step1: {
      businessInfomation: "Your business information";
      chooseType: "Choose a property type";
      businessName: "Your business name";
      businessDesc: "Describe your business";
      describe: "Describe...";
      additionalKeywords: "Additional keywords";
      exampleKeywords: "e.g., transportation, steamed rice rolls, nail services,...";
      chooseBusinessCats: "Choose the most suitable category for your business";
      businessCats: "Business Category";
      helperInfomation: "This information helps customers find you when they search for a business like yours.";
      exampleCats: "e.g. Restaurant, Beauty Salon,...";
    };
    step2: {
      countryRegion: "Country/Region";
      selectCountry: "Select your country/region from the dropdown";
      businessLocation: "Your business location";
      fullAddress: "Full address";
      thisAddress: "This is address show in contact and get location in map";
      exampleAddress: "e.g. house number street, state, city, country,...";
      street: "Street";
      state: "State";
      postalCode: "Postal code";
      detailAddress: "Detail address";
    };
    step3: {
      businessPicture: "Picture of your business";
      helperPicture: "A few beautiful photos will help customers have more sympathy for your property.";
      coverImage: "Cover image";
      picturesPlace: "Pictures of the place";
    };
    step4: {
      hour: "Hour";
      mainBusinessHour: "Set main business hour or mark your business as close.";
    };
    types: {
      business: "Business";
      company: "Company";
      organization: "Organization";
      privateBusiness: "Private business";
      other: "Other";
      jointStockCompany: "Joint stock company";
      limitedLiabilityCompany: "Limited liability company";
      stateOwnedEnterprise: "State owned enterprise";
      privateEnterprise: "Private enterprise";
      partnership: "Partnership";
      householdBusiness: "Household business";
    };
    contactTypes: {
      website: "Website";
      mobile: "Mobile";
      fax: "Fax";
      xcom: "xcom";
      phone: "Phone";
      email: "Email";
      facebook: "Facebook";
      linkedin: "Linkedin";
      other: "Other";
    };
    type: "Type";
    name: "Name";
    description: "Description";
    keyWords: "Key Words";
    categories: "Categories";
    businessInfo: "Business Infomation";
    basicInfo: "Basic infomation";
    logo: "Logo";
    photos: "Photos";
    changeLogo: "Change Logo";
  };
  auth: {
    name: "Name";
    emailAddress: "Email Address";
    password: "Password";
    forgotPassword: "Forgot password?";
    notHaveAccount: "Do not have an account?";
    confirmPassword: "Confirm password";
    alreadyAccount: "Already have an account?";
    signIn: "Sign in";
    createAccount: "Create an account";
    invalidEmailOrPassword: "Invalid email or password";
    accountNotVerify: "Account not verified";
    loginFail: "Login Failed";
    registerFail: "Register Failed";
    passwordRequired: "Password is required";
    emailRequired: "Email is required";
    nameRequired: "Name is required";
    minLengthPassword: "Password must be at least 8 characters long";
    passwordNotMatch: "Password do not match";
    emailExist: "Email had exists";
    verifyYourEmail: "Verify your email address";
    weHaveSentEmail: "we've sent an email to";
    toVerifyYourEmail: "to verify your email address and active your account. The link in your email will expire in 24 hours.";
    toResetYourPassword: "to reset your password. The link in your email will expire in 24 hours.";
    verifyFailed: "Verify Failed!";
    emailCouldntVerify: "Your email address could not be verified. Please try again!";
    verifySuccess: "verify successful!";
    verifiedAccountSuccess: "You have successfully verified account.";
    sendVerifyEmail: "Send verify email";
    send: "Send";
    accountVerified: "Your email have verified";
    emailNotExists: "Email not register";
    resendVerifyEmail: "Resend verify email";
    sendToQuickly: "Send email too quickly. Try again later!";
    checkEmailVerify: "Check your email to verify this email";
    sendForgotPassword: "Forgot password";
    reset: "Reset";
    resetPassword: "Reset Password";
    sendEmailSuccess: "we've sent an email to you";
    failedAction: "Some thing wrong. Please try again later!";
    invalidToken: "The token is invalid or has expired.";
    resetPasswordSuccess: "Your password has been successfully changed.";
  };
  businessPage: {
    manageNow: "Manage now";
    free: "Free";
    createNoCost: "Create a Business Profile at no cost";
    easy: "Easy";
    manageBusinessEasy: "Manage your profile from Search and Maps";
    personalized: "Personalized";
    addMoreInfo: "Add hours, photos, posts and more";
    claim: "Claim";
    createBusinessProfile: "Create a Business Profile, or manage an existing profile on Search and Maps";
    manage: "Manage";
    shareUpdatereview: "Share updates, respond to reviews, and connect with customers on VietSearch";
    showBestYourBusiness: "Show the best of your business";
    reachMore: "Reach more customers in three simple steps, with your free Business Profile.";
    standOutOnVS: "Stand out on VietSearch with a free Business Profile";
    turnPeopleFind: "Turn people who find you on VietSearch into new customers with a free Business Profile for your storefront or service area. Personalize your profile with photos, offers, posts, and more.";
    VSAds: "VietSearch Ads";
    businessWithVSAds: "Businesses get 2.5X more leads with VietSearch Ads";
    reachMoreCustomer: "Reach more customers who are searching for local businesses like yours.";
    prominentDisplay: "Prominent display on search and competitors' pages";
    onlyPay: "Only pay when interested people click on your ad";
    cancelAnytime: "Cancel anytime";
    addInfo: "Add important information";
    addInfoLike: "Add information like phone number, business hours, and safety and health measures so customers have the necessary details.";
    shareImage: "Share images, logos, and other visuals";
    introduceYourBusiness: "Introduce your business through photos, cover images, logos, and other visuals to stand out in front of customers.";
    showPeopleAboutYourBusiness: "Let people know about your business";
    addUniqueAttribute: "Add unique attributes so people can learn more about your business.";
    takeFirstImpression: "Take charge of your first impression";
    highlightEssentialInfo: "Highlight essential info and show what makes your business unique, right on your Business Profile.";
  };
  claim: {
    suggestEdit: "Suggest an edit";
    continue: "Continue";
    imOwner: "I'm own this business";
    imStaff: "I'm work at this business";
    imCustomer: "I'm a customer";
    relationshipToBusiness: "What’s your relationship to this business?";
    anyChangeMustVerified: "Any changes to a business page must be verified by VietSearch’s moderators.";
    claimThisBusiness: "Claim this page to unlock full access. It's totally free.";
    joinWithUs: "Join with us that can make updates like these and more directly from their VietSearch account. It’s...";
    continueWithLimited: "Continue editing with limited access";
    claimForFree: "Claim this page for free";
    updateBusinessDetail: "Update Business Details";
    suggestMustVerified: "Any suggested changes to a business page will first be verified by VietSearch’s moderators.";
    submitSuccess: "Submit successful";
    submitFail: "Submit failed";
    submit: "Submit";
    startClaim: "Hello! Let’s start with your business name";
    searchYourBusinessName: "Search for your business. If you can’t find it, you can add your business name so that we can help you claim your VietSearch Page.";
    yourBusinessName: "Your Business Name";
    addWithThisName: "Add your business with this name";
    businessRelicense: "Business relicense";
    receiveAt: "Receive verification code via email";
    submitNewInfo: "Submit with new information";
    chooseOptionClaim: "Choose a way to complete your claim";
    byContinue: "By continuing, you agree to VietSearch's <0>terms</0> and <1>privacy policy</1>. ";
    youAboutToClaim: "You are about to claim ";
    weWillSentEmailto: "We wil sent a verify email to <0>{{email}}</0>. Please check your email to continue next step.";
    claimSuccessful: "Claim business was successful!";
    gotoBusiness: "Visit Business";
    verifyClaimBusiness: "Verify claim business";
    reviewAndNotifyLater: "We will carefully review your information and notify you of the results via email as soon as possible.";
    requiredBusinessLicenses: "Business License Required";
    alreadyRequested: "Your request has already been submitted earlier and is currently being processed.";
    firstEmailInList: "The first email in the contact list will receive a response with the results";
    submitSuggestSuccess: "Business information edit suggestion submitted successfully!";
    searchOrAddBusiness: "Search or add business";
    listBusiness: "List business";
    nowYouCan: "Claim business was successful! Now you can:";
    manageYourBusiness: "Manage your business and update business page information.";
    viewBusinessStatistics: "View business statistics.";
    receiveAndRespondMessage: "Receive messages from potential customers and respond to reviews.";
  };
  common: {
    home: "Home";
    auth: {
      login: "Login";
      logout: "Log out";
      register: "Register";
    };
    explore: "Explore";
    myAccount: "My Account";
    privacy: "Security";
    term: "Terms & Conditions";
    wishlist: "Wishlist";
    darkTheme: "Dark theme";
    help: "Help";
    vietSearchForBusiness: "VietSearch for business";
    claimYourBusiness: "Claim your business";
    claimYourBusinessSubTitle: "Verify and manage businesses already on vietsearch";
    addYourBusiness: "Add your business";
    documentation: "Documentation";
    learnAboutBusinessVietSearch: "Learn more about VietSearch for business";
    uploadImage: "Upload a file";
    dragAndDrop: "or drag and drop";
    typeFile: "PNG, JPG, GIF up to 10MB";
    all: "All";
    share: "Share";
    save: "Save";
    confirm: "Confirm";
    unSave: "Un Save";
    coppy: "Coppy";
    shareBusiness: "Share Business";
    delete: "Delete";
    update: "Update";
    saveUpdate: "Save";
    edit: "Edit";
    view: "View";
    editBusiness: "Manage";
    viewBusiness: "View";
    showMore: "Show me more";
    viewAll: "View all";
    results: "results";
    menu: "Menu";
    null: "N/A";
    close: "Close";
    closeBusiness: "Close";
    continue: "Continue";
    countries: "Countries";
    regions: "Regions";
    categories: "Categories";
    types: "Types";
    filter: "filter";
    moreFilter: "More filter";
    seeAll: "See all";
    hidden: "Hidden";
    apply: "Apply";
    confirmDelete: "Confirm delete";
    confirmDeleteText: "Are you sure you want to delete this?";
    open: "Open";
    cancel: "Cancel";
    contacts: "Contacts";
    location: "Location";
    business: "Business";
    homepage: "Home Page";
    phone: "Phone";
    mobile: "Mobile";
    clearAll: "Clear all";
    search: "Search";
    support: "Support";
    businessTypes: {
      organization: "Organization";
      company: "Company";
      private_business: "Private business";
      other: "Other";
    };
    currency: "Currency";
    language: "Language";
    or: "Or";
    resendSuccess: "Verify code was resent successfully";
    requestNotFound: "Request Not Found";
    businessNotFound: "Business Not Found";
    weHaveSentOTP: "We have sent the OTP code to your email address. Please check your inbox.";
    checkYourEmail: "Please check your email for the OTP";
    emailNotFound: "Email contact not found";
    invalidEmailFormat: "Invalid email format";
    otpInvalid: "Invalid OTP code";
    optExpired: "OTP expired";
    notReceivedOTP: "Haven't received the OTP?";
    resend: "Resend";
    upto10MB: "up to 10MB";
    claimed: "Claimed";
    claimedTooltipText: "This business has been claimed by the owner or a representative.";
    unClaimed: "Unclaimed";
    unClaimedTooltipText: "This business has not yet been claimed by the owner or a representative.";
    hasExisted: "Has existed";
    notExisted: "Not existed";
    shareOn: "Share on";
    vi: "Tiếng việt";
    en: "English";
  };
  contact: {
    fullName: "Full name";
    emailAddress: "Email address";
    message: "Message";
    sendMessage: "Send message";
    VSname: "VIETSEARCH GLOBAL CO.,LTD";
    name: "Name";
    submitSuccess: "Submit successful!";
    submitFailed: "Submit Failed!";
  };
  dashBoard: {
    vietsearchExpert: "VietSearch Expert";
    myBusiness: "My business";
    reviews: "Reviews";
    password: "Account Password";
    wishlist: "Account Wishlist";
    account: "Account";
    photos: "Photos";
    seeAll: "See all";
    businessProgress: "Business progress";
    notFoundBusiness: "No businesses founded";
    notFoundPhotos: "No uploaded images founded";
    createYourBusiness: "Create your business now";
    btnCreateYourBusiness: "Create business";
    rightHere: "right here";
    createdBusiness: "Business created";
    showAllCreatedBusiness: "Here are all the businesses you've created on our platform";
    aboutVSBusiness: "About VietSearch Business";
    deleteConfirmation: 'Type "<strong>{{DELETE_CONFIRM_TEXT}}</strong>" to confirm the deletion:';
    deleteSuccess: "Delete successfully!";
    deleteFail: "Failed to delete! contact us!";
    deleteBusinessTitle: "Delete this business?";
    deleteBusinessHelpText: "<div className='p-5 space-y-5'><p>If you delete these businesses from your account:</p><ul className='list-disc ml-5 text-base space-y-2'><li>Some business information (name, address, etc.) will still appear on search engines like Google, Bing, etc.</li><li>All content on the VietSearch Business Page (website, posts, photos, videos, etc.) that you’ve published for these businesses will be deleted.</li><li>Linked VietSearch Ads campaigns will cease to function.</li><li>Anyone else managing the deleted businesses will lose access to them.</li><li>Data for deleted businesses cannot be recovered.</li></ul><p>If the business is closed, you should mark it as permanently closed before deleting it.</p><p>If you don’t want to delete a business, you can transfer ownership instead.</p></div>";
  };
  detail: {
    submit: "Submit your review";
    showAllPhotos: "Show all photos";
    writeReview: "Write your review";
    viewMap: "View map";
    businessInfo: "Business Infomation";
    reviews: "Reviews";
    placeHolderReview: "Describe your specific experience with this service";
    notHaveComments: "There are not have comments";
    claimTitle: "Is this your business?";
    claimDesc: "Claim your business to immediately update business infomation, respond to reviews, and more!";
    claimThisBusiness: "Claim this business";
    toViewBusinessStatistics: "to view business statistics, receive messages from prospective customers, and respond to reviews.";
    claimButton: "Verify this business";
    upload: "upload image";
    addImages: "Add Images";
    noteImageSize: "Please ensure all uploaded images are smaller than 5MB. Thank you!";
    missingValue: "Missing rating value";
    requestLogin: "Login to submit your review";
    updateReview: "Edit your review";
    createReview: "Write your review";
    selectRating: "Select your rating";
    dragOrDropHereOr: "Drag or drop here or";
    seeAllImages: "See all images";
    nearestBusiness: "Nearest business";
    until: "until";
    dayLater: "days later";
    tomorrow: "tomorrow";
    overallRating: "Overall rating";
    stars: "stars";
  };
  footer: {
    feature: "Feature";
    searchBusiness: "Search business";
    businessDashboard: "Manage business";
    community: "Community";
    information: "Information";
    aboutUs: "About us";
    teamVS: "Team VietSearch";
    sponsor: "Sponsor";
    recruitment: "Recruitment";
  };
  homepage: {
    heroTitle: "Services & Business";
    heroDesc: "With VietSearch you can search for Vietnamese businesses worldwide. Find new customers through the free Business Page";
    startSearch: "Start your search";
    suggestBusiness: "Suggestions for discovery";
    populaPlace: "Popular places to recommends for you";
    featuredPlaces: "Featured places";
    countBusiness: "20,000+ VIETNAMESE BUSINESSES";
    searchBusinessFree: "Search, post businesses, services completely free";
    userFriendly: "User friendly";
    globalization: "Globalization";
    support: "Support";
    simpleUse: "Simple, easy to use";
    simpleUseDesc: "Find everything you need. If you're a business, with just a few steps, you can also list your business and services on VietSearch.";
    reachGlobalCustomer: "Reach customers worldwide";
    reachGlobalCustomerDesc: "Opportunity to expand your customer base globally.";
    abroadServices: "Vietnamese businesses & services abroad";
    abroadServicesDesc: "Do you want to find Vietnamese service companies before studying abroad, traveling, or working overseas? Don't worry, VietSearch will assist you.";
    howItWork: "How it work";
    keepCalm: "Keep calm & travel on";
    bookRelax: "Book & relax";
    smartChecklist: "Smart checklist";
    saveMore: "Save more";
    eachTrip: "Let each trip be an inspirational journey, each room a peaceful space";
    joinGroup: "Join Associations and More";
    Over1000: "Over 1000+ Vietnamese Associations on VietSearch";
    theVideos: "The Videos";
    hottestVideos: "VietSearch in the News and on TV";
    mobileApp: "Mobile Apps";
    lorem: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed dapibus porttitor nisl, sit amet finibus libero.";
    catsSuggestion: "Suggestions categories";
    catsRecommend: "Some Categories to recommends for you";
    goodnews: "Good news from far away";
    peopleThink: "Let's see what people think of VietSearch";
    joinOutNewLetter: "Join our newsletter";
    readAndShare: "Read and share new perspectives on just about any topic. Everyone’s welcome.";
    getDiscount: "Get more discount";
    getMagazines: "Get premium magazines";
    enterEmail: "Enter your email";
    topAuthorMonth: "Top 10 author of the month";
    ratingBasedOn: "Rating based on customer reviews";
    becomeAHost: "Become a host";
    showMore: "Show me more";
    exploreNearby: "Explore nearby";
    discoverPlacesNearYou: "Discover great places near where you live";
    whyChooseUs: "Why did you choose us?";
    accompanyingUs: "Accompanying us, you have a trip full of experiences. With VietSearch, booking accommodation, resort villas, hotels, private houses, apartments... becomes fast, convenient and easy.";
    becomeAnAuthor: "Become an author";
  };
  openHours: {
    openMainHours: "Open with main hours";
    openMainHoursDesc: "Show when the business is open";
    openNoMainHours: "Open with no main hours";
    openNoMainHoursDesc: "Don't show any business hours";
    temporarilyClosed: "Temporarily closed";
    temporarilyClosedDesc: "Show that the business will open again in the future";
    permanentlyClosed: "Permanently closed";
    permanentlyClosedDesc: "Show that the business no longer exists";
    monday: "Monday";
    tueday: "Tueday";
    wednesday: "Wednesday";
    thursday: "Thursday";
    friday: "Friday";
    saturday: "Saturday";
    sunday: "Sunday";
    openAt: "Open at";
    closeAt: "Close at";
  };
  privacyAndTerm: {
    privacyContent: "<div className='space-y-4'><h3 className='font-medium text-lg'>Commitment to User's Personal Information Privacy</h3><p className='text-sm'>User's information is guaranteed to be absolutely confidential in accordance with the personal information protection policy. The collection and use of user information are only carried out with the user's consent, except when required by authorities. We do not use, transfer, provide, or disclose member's personal information to any third party without the member's permission.</p><p className='text-sm'>In the event that the server storing information is hacked, leading to the loss of member's personal data, the website management board will be responsible for notifying the authorities for timely investigation and notifying the members.</p><p className='text-sm'>In case the user discovers that their personal information is being misused or violated, they can file a complaint through our user support channel. Upon receiving these complaints, we will take all necessary measures to prevent further violations of that personal information, while also providing support to protect the user's legal rights and interests. Users have the right to file complaints about their personal information being disclosed to third parties to the website's management board. Upon receiving these feedbacks, we will verify the information, and be responsible for explaining the reason and guiding the member to restore and protect the information.</p><h3 className='font-medium text-lg'>Using Our Services</h3><p className='text-sm'>You must comply with all the policies provided to you within the scope of the Service. Unauthorized use of our Services is prohibited. For example, do not interfere with our Services or attempt to access them by any method other than through the interface and instructions we provide. You may only use our Services as permitted by law, including applicable export and re-export control laws and regulations. We may suspend or stop providing our Services to you if you do not comply with our terms or policies or if we are investigating suspected misconduct. Your use of our Services does not grant you ownership of any intellectual property rights in our Services or the content you access. You may not use content from our Services unless you obtain permission from the content owner or are otherwise permitted by law. These terms do not grant you the right to use any branding or logos used in our Services. Do not remove, obscure, or alter any legal notices displayed in or along with our Services.</p><h3 className='font-medium text-lg'>Privacy and Copyright Protection</h3><p className='text-sm'>VietSearch's privacy policy explains how we handle your personal data and protect your privacy when you use our Services. By using our Services, you agree that VietSearch can use such data in accordance with our privacy policy. We respond to notices of alleged copyright infringement and terminate the accounts of repeat infringers in accordance with the process set forth in Vietnam's Digital Millennium Copyright Act. We provide information to help copyright holders manage their intellectual property online. If you believe someone is infringing your copyright and want to notify us, you can find information on how to submit a notice and VietSearch's policy on responding to notices in our Help Center.</p><h3 className='font-medium text-lg'>Modifications and Termination of Our Services</h3><p className='text-sm'>We are constantly changing and improving our Services. We may add or remove functionalities or features, and we may suspend or stop a Service altogether. You can stop using our Services at any time, although we will be sorry to see you go. VietSearch may also stop providing Services to you or create new limits to our Services at any time. We believe that you own your data, and preserving your access to such data is important. If we discontinue a Service, where reasonably possible, we will give you reasonable advance notice and a chance to retrieve your information from that Service.</p></div>";
    termContent: "<div className='space-y-4'><h3 className='font-medium text-lg'>Welcome to VietSearch!</h3><p className='text-sm'>Thank you for using our products and services. The services are provided by VietSearch.</p><p className='text-sm'>By using our services, you agree to these terms. Please read them carefully.</p><h3 className='font-medium text-lg'>Purpose and Scope of Information Collection</h3><p className='text-sm'>Personal information of the members may be used by us for the following legitimate purposes:<br />+ Providing information about the service via email.<br />+ Used to analyze users' search trends with the aim of developing new services or improving existing services.<br />+ Used to contact members to exchange information on review boards and comments.<br />+ Used to respond to users' inquiries: we will respond to members via email, phone, or mail to the member's address when they have questions.<br /></p><h3 className='font-medium text-lg'>Scope of Information Usage</h3><p className='text-sm'>We are committed to using the information internally only for the purposes mentioned above.</p><h3 className='font-medium text-lg'>Information Retention Period</h3><p className='text-sm'>We will store personal information provided by the user on our internal systems while providing services to the user or until the purpose of collection is fulfilled or when the user requests to delete the provided information.</p><h3 className='font-medium text-lg'>Address of the Personal Information Collection and Management Unit</h3><p className='text-sm'>VietSearch website: https://www.vietsearch.org</p></div>";
  };
  search: {
    recentSearch: "Recent searches";
    thingToDo: "things to do, nail salons, plumbers";
    locationInfo: "address, neighborhood, city, state or zip";
    whatFinding: "What are you finding?";
    whereGoing: "Where are you going?";
    searchBusiness: "Search business";
    searchLocation: "Search location";
    anyWhereAnyBusiness: "Anywhere • Any business";
    notResult: "WE ARE SORRY. THERE ARE NO RESULTS FOR YOUR FILTER.";
    clickReset: "Click Reset filter to start a new search";
    resetFilter: "Reset filter";
    showMap: "Show Map";
    searchMovingMap: "Search as I move the map";
  };
  testimonial: {
    minhTuan: {
      name: "Minh Tuan";
      position: "Marketing Director";
      content: "VietSearch has significantly boosted my online presence. With the free Business Page, I can easily showcase my services and products, attracting more potential customers. The platform also allows me to personalize my page to stand out even more.";
    };
    lanAnh: {
      name: "Lan Anh";
      position: "Business Owner";
      content: "Using the free Business Page on VietSearch has been a game-changer for my business. I can easily create a personalized page with special offers, photos, and detailed information, helping me attract new customers and expand my market.";
    };
    hoangNam: {
      name: "Hoang Nam";
      position: "Sales Manager";
      content: "The free Business Page on VietSearch helps me stand out in search results. By personalizing my page, I’ve been able to attract many new customers and increase revenue for my company.";
    };
    thaoVy: {
      name: "Thao Vy";
      position: "CEO";
      content: "VietSearch not only helps me find new customers but also allows me to build a professional Business Page that’s easy to customize with offers and posts. It’s an incredibly useful tool for growing a business.";
    };
    quangHuy: {
      name: "Quang Huy";
      position: "Sales VIP";
      content: "VietSearch has helped us connect with target customers quickly and effectively. The free Business Page lets me update offers, images, and detailed service information, making our store stand out on the platform.";
    };
  };
  wishlist: {
    wishlist: "Wishlist";
    nothingHere: "Please add the business to your favorites list!";
  };
}

export default Resources;
